Repository eagles-project/haero, pull requests merged in 2022-11, with the labels that each got.

#415 Using EKAT's generated list of libs instead of listing them manually.
  ext/CMakeLists.txt
Labels: build_system

#416 Various fixes for new EKAT
  .github/workflows/auto_test.yml
  CMakeLists.txt
  README.md
  cmake/haero.cmake.in
  ext/CMakeLists.txt
  setup
Labels: third-party libs, build_system

#418 Readding (optional) mechanism for specifying Kokkos device architecture.
  setup
Labels: build_system, GPU, kokkos

#419 Strip down AeroSpecies class for Cuda compiler.
  haero/aero_species.hpp
Labels: GPU

#420 Gas species is now a simple (C-style) struct.
  haero/gas_species.hpp
Labels: GPU

#422 Clarified some comments for the Atmosphere class.
  haero/atmosphere.hpp
Labels: documentation

#423 Haero un-Packed!
  .github/workflows/auto_test.yml
  CMakeLists.txt
  haero/CMakeLists.txt
  haero/aero_process.hpp
  haero/aero_species.hpp
  haero/aero_utils.hpp
  haero/atmosphere.cpp
  haero/atmosphere.hpp
  haero/check.hpp
  haero/constants.hpp
  haero/floating_point.hpp
  haero/gas_species.hpp
  haero/haero.hpp
  haero/haero_config.hpp.in
  haero/math.hpp
  haero/root_finders.hpp
  haero/tests/CMakeLists.txt
  haero/tests/math_tests.cpp
  haero/tests/math_tests.hpp
  haero/tests/view_pack_helper_tests.cpp
  haero/utils.cpp
  haero/utils.hpp
  haero/view_pack_helpers.cpp
  haero/view_pack_helpers.hpp
  setup
Labels: cleanup

#424 Minor touch-ups (C++ formatting rules, new machine file)
  .clang-format
  .github/workflows/auto_test.yml
  .github/workflows/clang-format-check.yml
  CMakeLists.txt
  README.md
  docs/installation.md
  haero/aero_process.hpp
  haero/aero_species.hpp
  haero/aero_utils.hpp
  haero/atmosphere.cpp
  haero/atmosphere.hpp
  haero/floating_point.hpp
  haero/gas_species.hpp
  haero/haero.hpp
  haero/math.hpp
  haero/root_finders.hpp
  haero/tests/math_tests.cpp
  haero/tests/math_tests.hpp
  haero/utils.cpp
  haero/utils.hpp
  machines/compy.sh
  machines/constance.sh
  machines/cori.sh
  machines/deception.sh
  machines/marianas.pnl.gov.sh
  machines/s1024454.sh
  machines/s1061858.sh
  setup
  tools/update_version_info.sh
Labels: cleanup, reconfig required
